export const SETTINGS_FIELDS = [
  "KIRACLAW_AGENT_NAME",
  "KIRACLAW_PROVIDER",
  "KIRACLAW_MODEL",
  "ANTHROPIC_API_KEY",
  "OPENAI_API_KEY",
  "SLACK_BOT_TOKEN",
  "SLACK_APP_TOKEN",
  "SLACK_SIGNING_SECRET",
  "SLACK_TEAM_ID",
  "SLACK_ALLOWED_NAMES",
  "CHROME_ENABLED",
  "PERPLEXITY_ENABLED",
  "PERPLEXITY_API_KEY",
  "GITLAB_ENABLED",
  "GITLAB_API_URL",
  "GITLAB_PERSONAL_ACCESS_TOKEN",
  "MS365_ENABLED",
  "MS365_CLIENT_ID",
  "MS365_TENANT_ID",
  "ATLASSIAN_ENABLED",
  "ATLASSIAN_CONFLUENCE_SITE_URL",
  "ATLASSIAN_JIRA_SITE_URL",
  "ATLASSIAN_CONFLUENCE_DEFAULT_PAGE_ID",
  "TABLEAU_ENABLED",
  "TABLEAU_SERVER",
  "TABLEAU_SITE_NAME",
  "TABLEAU_PAT_NAME",
  "TABLEAU_PAT_VALUE",
  "FILESYSTEM_BASE_DIR",
  "KIRACLAW_DESKTOP_CHAT_ENABLED",
  "KIRACLAW_PROACTIVE_AUTO_DISPATCH",
];

export const BOOLEAN_FIELDS = [
  "PERPLEXITY_ENABLED",
  "GITLAB_ENABLED",
  "MS365_ENABLED",
  "ATLASSIAN_ENABLED",
  "TABLEAU_ENABLED",
  "CHROME_ENABLED",
  "KIRACLAW_DESKTOP_CHAT_ENABLED",
  "KIRACLAW_PROACTIVE_AUTO_DISPATCH",
];

export const SELECT_DEFAULTS = {
  KIRACLAW_PROVIDER: "claude",
  PERPLEXITY_ENABLED: "false",
  GITLAB_ENABLED: "false",
  MS365_ENABLED: "false",
  ATLASSIAN_ENABLED: "false",
  TABLEAU_ENABLED: "false",
  CHROME_ENABLED: "false",
  KIRACLAW_DESKTOP_CHAT_ENABLED: "true",
  KIRACLAW_PROACTIVE_AUTO_DISPATCH: "false",
};

export const DEFAULT_CHAT_SESSION_ID = "desktop:local";

export const EXTERNAL_MCP_SERVER_NAMES = [
  "perplexity",
  "gitlab",
  "ms365",
  "atlassian",
  "tableau",
  "playwright",
];

export const EXTERNAL_MCP_CONFIG_FIELDS = {
  playwright: "CHROME_ENABLED",
  perplexity: "PERPLEXITY_ENABLED",
  gitlab: "GITLAB_ENABLED",
  ms365: "MS365_ENABLED",
  atlassian: "ATLASSIAN_ENABLED",
  tableau: "TABLEAU_ENABLED",
};
