export const state = {
  activeView: "overview",
  appMeta: null,
  config: {},
  daemonStatus: null,
  engineAction: {
    action: null,
    busy: false,
    message: "",
    tone: "neutral",
    visible: false,
  },
  runtime: null,
  skills: null,
  schedules: [],
  scheduleFile: "",
  scheduleError: "",
  runLogs: [],
  runLogFile: "",
  runLogError: "",
  settingsDirty: false,
};
